class BusInfo < ActiveHash::Base
  self.data = [{:id => 672, :route_1 => {:destination => "大鵬新城", :stops => [{:id => 1, :stop_name => "三民路"},
    {:id => 2, :stop_name => "三民健康路口（西松高中）"},
    {:id => 3, :stop_name => "健康新城"},
    {:id => 4, :stop_name => "長壽公園"},
    {:id => 5, :stop_name => "三軍總醫院松山分院"},
    {:id => 6, :stop_name => "南京新村"},
    {:id => 7, :stop_name => "博仁醫院"},
    {:id => 8, :stop_name => "台北市區監理所（光復）"},
    {:id => 9, :stop_name => "捷運國父紀念館站（光復）"},
    {:id => 10, :stop_name => "國父紀念館"},
    {:id => 11, :stop_name => "市民住宅"},
    {:id => 12, :stop_name => "三張犁"},
    {:id => 13, :stop_name => "光復南路口"},
    {:id => 14, :stop_name => "三興國小（臨江街觀光夜市）"},
    {:id => 15, :stop_name => "喬治商職"},
    {:id => 16, :stop_name => "捷運六張犁站（基隆路）"},
    {:id => 17, :stop_name => "和平高中"},
    {:id => 18, :stop_name => "基隆長興街口"},
    {:id => 19, :stop_name => "台大癌醫（基隆路）"},
    {:id => 20, :stop_name => "臺灣科技大學"},
    {:id => 21, :stop_name => "公館"},
    {:id => 22, :stop_name => "福和橋（林森路）"},
    {:id => 23, :stop_name => "永元路"},
    {:id => 24, :stop_name => "秀朗國小"},
    {:id => 25, :stop_name => "得和路"},
    {:id => 26, :stop_name => "中興新村"},
    {:id => 27, :stop_name => "中興二村"},
    {:id => 28, :stop_name => "智光商職"},
    {:id => 29, :stop_name => "南勢角（景平路）"},
    {:id => 30, :stop_name => "捷運景平站"},
    {:id => 31, :stop_name => "景平路景德街口"},
    {:id => 32, :stop_name => "捷運秀朗橋站"},
    {:id => 33, :stop_name => "中正環河路口"}
]}},

      ]
end
